SELECT round(avg(SALARY), 2) as AVERAGE_SALARY, COUNTRY_NAME
from EMPLOYEES
    join DEPARTMENTS using (DEPARTMENT_ID)
    join LOCATIONS using (LOCATION_ID)
    join COUNTRIES using (COUNTRY_ID)
GROUP BY COUNTRY_NAME
ORDER BY avg(SALARY)

