SELECT DISTINCT EMPLOYEES.FIRST_NAME, FIRST_NAME_COUNT_TABLE.FIRST_NAME_COUNT
FROM EMPLOYEES join (
SELECT FIRST_NAME, count(FIRST_NAME) as FIRST_NAME_COUNT
FROM EMPLOYEES
GROUP BY FIRST_NAME) FIRST_NAME_COUNT_TABLE
ON EMPLOYEES.FIRST_NAME = FIRST_NAME_COUNT_TABLE.FIRST_NAME
ORDER BY FIRST_NAME_COUNT_TABLE.FIRST_NAME_COUNT DESC, EMPLOYEES.FIRST_NAME

