WITH
    SALARY_PER_DEPARTMENT as (
        SELECT DEPARTMENT_ID, coalesce(sum(SALARY), 0) as DEPARTMENT_SALARY
        FROM DEPARTMENTS full join EMPLOYEES using (DEPARTMENT_ID)
        GROUP BY DEPARTMENT_ID
    ),

    TOTAL_SALARY as (
        SELECT sum(SALARY) as TOTAL
        FROM EMPLOYEES
    )

SELECT DEPARTMENT_ID, DEPARTMENT_SALARY, round(100 * DEPARTMENT_SALARY / TOTAL) as SALARY_PERCENT
FROM SALARY_PER_DEPARTMENT, TOTAL_SALARY
ORDER BY SALARY_PERCENT DESC

